# Generated by Django 5.1.6 on 2025-03-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
